version: 2

defaults: &defaults
  docker:
    - image: acro5piano/circleci-docker-image-node-10.3.0-awscli-ansible
    - image: postgres:10-alpine
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: minhori_testing
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: setup
          command: |
            cp .env.local .env
            cp firebase-adminsdk.example.json firebase-adminsdk.json
      - run:
          name: check ts
          command: |
            yarn tsc
            # TODO: Run test in CI
            # yarn test
  deploy:
    <<: *defaults
    steps:
      - run:
          name: deploy
          command: |
            curl -XPOST -H "Content-Type: application/json" -d '{
              "build_parameters": {
                "CIRCLE_JOB": "deploy"
              }
            }
            ' "$WEBHOOK_URL"

workflows:
  version: 2
  master_jobs:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
